// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BuscaPublicaTJeMG.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace BuscaPublicaTJeMG.Models.Configurations
{
    public partial class ParticipanteConfiguration : IEntityTypeConfiguration<Participante>
    {
        public void Configure(EntityTypeBuilder<Participante> entity)
        {
            entity.HasOne(d => d.IdProcessoNavigation)
                .WithMany(p => p.Participante)
                .HasForeignKey(d => d.IdProcesso)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_Participante_Processo");

            OnConfigurePartial(entity);
        }
        partial void OnConfigurePartial(EntityTypeBuilder<Participante> entity);
    }
}
